Public/auto-write-text.html
Public/digital_clock.html
Public/purple_heart.html
Public/toast_notification.html
assets/Js/auto-write-text.js
assets/Js/digital_clock.js
assets/Js/purple_heart.js
assets/Js/toast_notification.js
assets/css/auto-write-text.css
assets/css/digital_clock.css
assets/css/purple_heart.css
assets/css/toast_notification.css

1.Toast notification added
2.Digital clock added
3.Falling purple-hearts added

More projects added

---

Public/word-count-calculator.html
assets/Js/word-count-calculator.js
assets/css/word-count-calculator.css

Here is a code for word count web app for issue number #11 . Please accept the PR asap.

 #11 Adding word count calculator

---

Public/photo_site.html
assets/css/photo_site.css

added photo site project

---

Public/maps.html
assets/Js/maps.js
assets/css/maps.css

mapsApi added

---

Public/bmi-calculator.html
Public/height-converter.html
assets/Js/bmi-calculator.js
assets/Js/height-converter.js
assets/css/bmi-calculator.css
assets/css/height-converter.css

Adding BMI calculator in response to #11

#11 Adding BMI calculator web-app

---

Public/NGO.html
assets/css/NGO.css

this simple website is built using HTML and CSS and is powered by Razorpay API and gateway
This is in reference to #50

NGO website with Payment gateway Integrated

---

Public/countdown-timer.html
assets/Js/countdown-timer.js
assets/css/countdown-timer.css

Please merge this PR for countdown web app after verification.

#11 Added Count down web app

---

Public/todo.html
Public/word-count-calculator.html
assets/Js/todo.js
assets/Js/word-count-calculator.js

Added functionality to word counter

---

Public/aipanArt.html

Please accept it under Hacktober Fest 2021.

Added aipanArt website. 

---

Public/resume_builder.html
assets/Js/resume_builder.js
assets/css/resume_builder.css

issue no #78 
Hello sir,
I added a html, css and js based resume builder where you can fill in your details in a professionally designed resume and download the resume in pdf format.
I would be very glad if you accept my pr
the file name is resume_builder in the assets folder

resume builder added

---

Public/loan-calculator.html
assets/Js/loan-calculator.js
assets/css/loan-calculator.css

#71  Adding Loan Calculator Web App

---

Public/responsive_nav.html
assets/css/responsive_nav.css

issue #80 
has been added
Professionally designed fully responsive navbar for any of your projects

Responsive navbar added

---

Public/stone_paper_scissors.html
assets/Js/stone_paper_scissors.js
assets/css/stone_paper_scissors.css

Stone Paper Scissors Game

---

Public/auto_image_slider.html

I have added a new project which changes background image automatically and it can be used to give scrolling image animation effects to a website .

Added a new automatic image slider animation project

---

Public/accordion.html

https://user-images.githubusercontent.com/87171452/144737171-c0929e8a-f709-4919-a8c1-090e6561a974.mp4

Added a code to accordion

---

Public/Quiz_app/Quiz_app.html
assets/Js/Quiz_app.js
assets/css/Quiz_app.css

https://user-images.githubusercontent.com/87171452/146484550-541c4117-9695-4b87-9b8e-d619d0325476.mp4

Added a code to quiz website

---

Public/Report_Calculator/ReportCalculator.html
assets/Js/ReportCalculator.js
assets/css/ReportCalculator.css

https://user-images.githubusercontent.com/87171452/146487578-41d19d15-f7a4-4c31-b10b-c5cbb4a91f95.mp4

Added Code to Student Report Calculator

---

Public/Speed_Typer/Speed_Typer.html
assets/Js/Speed_Typer.js
assets/css/Speed_Typer.css

Added a code to speed typer

---

Public/colorchooser.html
assets/Js/colorchooser.js
assets/css/colorchooser.css

Added a code to choose background color

---

Public/confirmpasswordvalidator.html
assets/Js/confirmpasswordvalidator.js
assets/css/confirmpassword.css

https://user-images.githubusercontent.com/87171452/146547510-4bdbb797-fd90-484c-993f-5dcaa29faa43.mp4

Added a code to confirm password in a form

---

Public/EmailValidator.html
assets/Js/EmailValidator.js
assets/css/EmailValidator.css

Added a Code to Email Validation

---

index.html

Earlier Images were not visible at https://zerooctave.github.io/ZeroOctave-Javascript-Projects/
I have fixed this bug, you can review it.
**PREVIOUSLY**
After Fixing this bug...
**NOW**

Fixed Images Visibility in gh-pages

---

script.js

This is the code for ***script.js***

Code for script.js

---

Public/calculator.html

#171 
checkout the below link for the working of the solution 
https://siva-krish45.github.io/ZeroOctave-Javascript-Projects/
when u click the **try now** button on the calculator app, now it shows the calculator UI .

calculator app opening issue solved

---

Public/guess_color.html
assets/css/guess_color.css
index.html

#181 
Changes has been done in guess_color.html file in line 9 and 24 and in index file at line #265.
a) Defined the proper path of js file in guess_color.html file.
b) Added script tag to link the guess_color.js file in index.html.
**Before**
**After**

Guess_Color issue has been resolved

---

style.css

#241 
Changed the CSS of the paragraph element, so that description of the object is visible on the white background.
Before
After
✅ My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
✅ This PR does not contain plagiarized content.
✅ My Addition/Changes works properly and matches the overall repo pattern.
✅ The title of my pull request is a short description of the requested changes.

changed color of passage to make it visible

---

index.html

#249 
Renamed the id of the card, as it is getting clashing with another id.
Before
https://user-images.githubusercontent.com/73388412/156507517-adba661b-f7d1-4c17-b8a7-6610e8afdc27.png
After
✅ I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
✅ I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
✅ I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

the id of the card displayed is renamed

---

Public/GitHub-Profiles.html
assets/Js/GitHub-Profiles.js
assets/css/GitHub-Profiles.css

Closes #303 
I have added all the relevant files related to the GitHub-Profiles Application

Fixed the issue #303

---

Public/animeApp.html
assets/css/animeApp.css

Added Random anime profile pic generator to the project list

---

Public/Speed_Typer.html

Imported Css and Js files in the program correctly.

Speed_Typer Program modified

---

Public/loginform.html
assets/Js/loginform.js
assets/css/loginform.css

Login form new design

---

Public/counter.html
assets/Js/counter.js
assets/css/counter.css

- I added dark mode to counter
There was no bug in the counter. it was my first open-source contribution
so I added  a dark mode
_I am gssoc 2022 contributor _
https://user-images.githubusercontent.com/96793524/157536711-c8686449-475e-4396-98a8-bf1ab1563891.mp4

Added Dark Mode to counter

---

README.md

**### 🛠️ Fixes Issue #359**  
Closes #359  
**### 👨‍💻 Changes proposed**
1. Updated the projects systematically as shown on the website
2. Added new projects displayed on the website as of 14th March 2022.
**### ✅ Check List (Check all the applicable boxes)** 
**### 📄 Note to reviewers**
I will be adding and updating the new projects every week if there are any changes like that on the website.
**### 📷 Screenshots**

Add projects in README.md

---

Public/restaurant/about.html
Public/restaurant/menu.html
Public/restaurant/restaurant.html
assets/css/restaurant/restaurant.css

Closes #365 
1. About option in navbar directs to a separate About page instead of the footer.
2. Options in navbar when clicked open in the same tab instead of a new tab (bug fixed)
Kindly let me know if I have to add any more changes

Added a seperate About page for the restaurant website

---

Public/bmi-calculator.html
assets/css/bmi-calculator.css
index.html

I'm GSSOC Participant
issue closed already #270 opening again!
1. I have improved the UI OF BMI Calculator Project and I again got some suggestions like CSS file is not working properly and I changed it and it was merged after that.
2. But still there is some issue in my project as external file links like CSS and Javascript files are not Linked properly to the HTML file and images also not linked. So I opened the issue again now.
3. Now I had made all the changes and it working now properly!
4. Kindly, check to it and merge my Pull Request.

Successfully fixed the issue of Unworking file links of BMI Calculator issue#270

---

index.html
style.css

Added a search bar under the "JavaScript Projects" header.
When the user will type a required project in the search bar and click on the search icon, that particular project website will open for the user.
like in the above example, on pressing the search icon, the analog clock website will open up in another tab.

Add Searchbar for the projects

---

index.html
style.css

Closes #391 
Added a button which scrolls to top of the page.

scroll To Top botton added

---

assets/Js/counter.js
assets/Js/word-count-calculator.js

The counter feature is now working properly . On clicking increase button , it increments the count by one and on clicking decrease button it decrements the count by one . Reset button resets the count to zero .

Solved issue #319 . Counter feature working properly

---

index.html
style.css

Closes issue number #426 
👨‍💻 Changes proposed
The back to top button was not working. Fixed that issue. If the user now clicks the button, they will be navigated to the top of the website. Also towards the end of the site, the button went in the back of some tiles. Fixed that too. Now the button will be visible throughout the website.
https://user-images.githubusercontent.com/91081814/161385415-2b824df1-081b-471b-8bac-92cf32329bef.mp4

Back to top button bug resolved

---

Public/CaesarCipher.html
assets/css/CaesarCipher.css

#450 
Modified the code to work properly.

 CaesarCipher Program modified

---

style.css

Just did some of the required changes in the CSS file to make it more good looking in smaller screens

added responsiveness

---

index.html

🛠️ Fixes Issue #545 
Minor path related issue solved .
Now the  favicon is visible.
Have a look on favicon now.

Fixed the issue on fevicon now the favicon is visible.

---

Public/gravity.html
assets/Js/gravity.js
assets/css/gravity.css

Added a new gravity simulator which simulates the motion of bodies in spaces and how they interact with one another via gravity. Objects mass and velocities as well as initial position can be set so that desired motion is obtained. Added a cool background to the project too.

Added gravity simulator

---

cards.json

Update cards.json for URL Keeper

---

Public/aipanArt.html

Closes #588 
Added hover effect to nav bar
Corrected anchor tag
- [X ] This PR does not contain plagiarized content.
Open Al Panart and see the difference

Added hover effect to navbar in Al Panart  resolved issue #588

---

cards.json

Modified links in cards.json of Images that were not showing up on website.
GSSoC Contributor

Fixed Image links that were not visible

---

Public/GitHub-Profiles.html

***file linking wrong of Js*** 
***CSS tag link wrong***
***meta tag wrong***

GitHub profile not work

---

cards.json

mention link wrong in card.json file

word-search-image

---

assets/css/meditation.css

Made responsive
Closes #689 
Updated meditation.css for increasing responsiveness

Made meditation website responsive

---

Public/accordion.html

Changed title in accordion page.

Changed title to Accordion from document.

---

README.md
cards.json

Corrected readme and cards.json . Please review once .

Corrected readme and cards.json

---

Public/counter.html

The src link was not correct and thus not linking to the correct script. Fixed that.

fixed the src link in script tag of counter.html

---

Public/BaseX_Calculator.html
assets/css/BaseX_Calculator.css

Enhanced interface design and allignment

Enhanced the UI of the BaseX calc section 

---

assets/css/to-do.css

- [ ✅] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [✅ ] This PR does not contain plagiarized content.
- [ ✅] My Addition/Changes works properly and matches the overall repo pattern.
- [ ✅] The title of my pull request is a short description of the requested changes.
Updated background to cover the whole screen.
After:
Before:
added screenshots

Update background size - cover

---

Public/gym-website.html

trainer spelling corrected in gym-website
- [✓ ] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [✓ ] This PR does not contain plagiarized content.
- [✓ ] My Addition/Changes works properly and matches the overall repo pattern.
- [✓ ] The title of my pull request is a short description of the requested changes.

trainer spelling corrected in gym-website

---

Public/guess-the-number.html

Closes#815 
Earlier Check and Again button on being clicked showed no response but now the issue is fixed.
When the Check button is being clicked, there is a response - Too high or Too Low or Correct Number
Similarly the Again button is also working
This issue is resolved under SSOC'22
Before 
After

Updated guess-the-number.html Check and Again button are now responding

---

Public/BooksLibrary.html

1. Book Type label added.
2. Type of book is now clickable.
3. Formatted entire code base for better indentations.
[Deployment link](https://zerooctave.github.io/ZeroOctave-Javascript-Projects/Public/BooksLibrary.html)

Book type button click fix

---

index.html
script.js
style.css

Added a Day-Night Toggle Button

---

Public/popup.html

[SSOC]
fixed basic typo which prevented working of popup project.

fixed typo issue

---

README.md

Updated the README.md
In continuation with the PR #854

Update README.md for including my "SimplyRecipes" website in it.

---

assets/Js/weather_app.js
assets/css/weather_app.css

Issue number : 875
- Added Humidity and windspeed while rendering the temperature.

added humidity and windspeed

---

Public/tip_calculator.html
assets/css/tip_calculator.css

modified tip calculator with tailwind CSS

modified tip calculator with tailwind css

---

assets/css/book.css

#838 
Changed colors & size of Bottom Navbar Icons on Book N Buy Project for better visuality.
Color Change, Size Change
Now users will have better visuality to bottom navbar icons.

Changed color & size of bottom Navbar Icons on Book N Buy Project

---

README.md

Hacktoberfest logo was not visible.

---

README.md

Corrected Year

---

Public/calculator.html
assets/Js/Calculator.js
assets/css/Calculator.css

Added a new column of buttons for  兀,  e,   x^2,  x^y,  sqrt(x)  and  log(x)  operations.

Added buttons for  x^2,  x^y,  sqrt(x),  log(x) ,  兀,  e in Calculator

---

Public/resume_builder.html
assets/Js/resume_builder.js
assets/css/resume_builder.css

Added remove button in each section, to delete the extra or unwanted fields of respective sections.
Screenshot of UI of Resume Builder after adding the remove buttons.

Added the remove button in each section

---

Public/noteapp.html

Please consider this as a Hacktoberfest accepted label to your repo.
Added clear button
Improved some text

added clear button

---

index.html

Improved keywords in html file

---

style.css

Gradient color added!(can change the hash color as per your choice)

---

Public/rgbmixer.html
assets/Js/rgbmixer.js
assets/css/rgbmixer.css

Closes #954 
Added sliders for acquiring RGB values
Displayed the value of each slider (0-255)
Implemented an output div to show the output color
Changed the background color to be a gradient rather than a solid fill

Enhanced UI of RGB Mixer

---

index.html
style.css

Added hover to the arrow button which makes the site more responsive and enhances user experience.  
- [✅] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [✅] This PR does not contain plagiarized content.
- [✅] My Addition/Changes works properly and matches the overall repo pattern.
- [✅] The title of my pull request is a short description of the requested changes.
When cursor is hovered over the button:

Added hover feature to the arrow button

---

Public/QR_Code_Generator.html
Public/bmi-calculator.html
Public/vaccineslot.html
assets/css/Calculator.css
assets/css/bmi-calculator.css
assets/css/vaccineslot.css

#961 
Restructured the UI of CoWin Slot Notifier
*Before:*
*After:*

Made some changes

---

index.html

The email icon which was not working properly is now fixed. It redirects the user to the email address which enhances the overall user experience.
- [✅] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [✅] This PR does not contain plagiarized content.
- [✅] My Addition/Changes works properly and matches the overall repo pattern.
- [✅] The title of my pull request is a short description of the requested changes.
When link is clicked, it redirects the user:

Fixed the email link

---

Public/incrementinator.html
assets/Js/incrementinator.js
assets/css/incrementinator.css

i added button hover effect to the buttons and also changes the font family to make the website more attractive and better

added animations to the buttons

---

Public/BooksLibrary.html
Public/auto_image_slider.html

Updated the header

---

assets/css/crypto_app.css

added box-shadow and border-radius to cards displaying the coins to make them more good looking and user friendly

added box-shadow and border radius to cards

---

Public/shell_game.html
assets/Js/shell_game.js
assets/css/shell_game.css

In shell game, the UI was not that good and the section of label was intersecting the gif part.
I corrected the UI.
older one:
newer one:

enhanced ui

---

Public/Speed_Typer.html
assets/Js/Speed_Typer.js
assets/css/2048.css
assets/css/Speed_Typer.css
assets/css/dice_game.css

Done Few Changes 2048 and Speed_typer
2048 : Changes it's UI and some CSS 
speed_typer : Changes it's Difficulty Levels like Easy, Medium and Hard, Change in UI and some modification in javaScript
- [✅] My code doesn't break any part of the project (Zero Octave-Javascript-Projects).
- [✅] This PR does not contain plagiarized content.
- [✅] My Addition/Changes works properly and matches the overall repo pattern.
- [✅] The title of my pull request is a short description of the requested changes.

2048 Game and Speed_typer

---

Public/happy_hacktober/happyhactober.html
Public/travel-website.html
assets/css/dadsjoke.css

The website was not responsive besides, it was not in a condition to use for a small screen size.
Also, the styling was not that good and was not looking good.
I made the corrections and now everything is fine.
older:
newer:

fixed responsiveness

---

Public/happy_hacktober/happyhactober.html
Public/travel-website.html

The navbar styling was not regular, on hovering the element, the effect was also showing on pipes which were used as a separator but hovering was not separating it.
I made the changes and made the navbar styling completely regular.
older:
newer:

Navbar styling fixed

---

assets/Js/dictionary.js

Fix audio feature for Dictionary app

---

Public/employeeDatabase.html
assets/Js/employeeDatabase.js

- Added Form Validations for the Employee Database project which includes: 
- valid date format for Joining Date
- valid salary value that's greater than or equal to 0
- avoid inserting duplicated emp-code

Added form validation for Employee database project

---

index.html
script.js
style.css

made Toggle Button working
made some changes to the Back-to-top button because it was getting hidden behind the cards.

made  toggle button working as well as made some changes for back-to-top button

---

Public/Analog_clock.html
assets/Js/analog_clock1.js
assets/css/Analog_clock.css

Closes #976  
I have added a toggle checkbox that allows us to switch between light and darkmodes. For this I have used basic java script to change the colors based on the status of the checkbox.
As the color of the numbers on the clock is fixed, we couldn't change them. However grey suits both the themes. Here is the preview of light and dark mode UI/UX designs of Analog clock.

added dark mode for analog clock

---

Public/word-count-calculator.html
assets/Js/word-count-calculator.js

👨‍💻 Changes proposed
I have used basic JavaScript to add a new feature i.e. to display the longest word in text and the length of the longest word.
Above changes are made in the Live Word Counter project.
✅ Check List (Check all the applicable boxes) 
📷 Screenshots

Longest Word
